language: php

# php compatibility
php: ['7.3', '7.4']

cache:
  - directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer install --no-interaction --no-progress --prefer-dist
  - bash develop/install-development-tools

script:
  - tools/phpcs -sp src/ tests/
  - tools/php-cs-fixer fix --dry-run --verbose
  - vendor/bin/phpunit --testdox --verbose
  - tools/phpstan analyse --level max --no-progress --verbose src/ tests/
  - tools/psalm --no-progress
  - phpdbg -qrr tools/infection --no-progress --no-interaction --show-mutations || true

notifications:
  email:
    if: branch = master
